target 'Example' do
  platform :ios, '8.0'
	use_frameworks!
  pod 'SwiftIconFont', :path => '../'
end

target 'ExampleMac' do
  platform :osx, '10.9'
  use_frameworks!
  pod 'SwiftIconFont', :path => '../'
end
